#!/bin/bash

docker build -t gfyrag/docker-registry-builder:x86_64 -f Dockerfile.builder .
docker run gfyrag/docker-registry-builder:x86_64 > rootfs.tar
docker build -t gfyrag/docker-registry:x86_64 .
rm rootfs.tar
