#!/bin/bash

docker build -t gfyrag/syslogd-klogd-builder:x86_64 -f Dockerfile.builder .
docker run gfyrag/syslogd-klogd-builder:x86_64 > rootfs.tar
docker build -t gfyrag/syslogd-klogd:x86_64 .
rm rootfs.tar
